-- Supabase schema for student voting system

CREATE TABLE candidates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  position TEXT NOT NULL,
  department TEXT NOT NULL,
  manifesto TEXT NOT NULL,
  initials TEXT NOT NULL
);

CREATE TABLE votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id BIGINT REFERENCES candidates(id) ON DELETE CASCADE,
  student_id TEXT NOT NULL UNIQUE,
  student_name TEXT NOT NULL,
  department TEXT NOT NULL,
  voted_at TIMESTAMPTZ DEFAULT NOW()
);

-- Optional seed data
INSERT INTO candidates (name, position, department, manifesto, initials) VALUES
('Aisha Rahman', 'Student President', 'Computer Engineering', 'Leading innovation, mentoring students, and improving campus digital services.', 'AR'),
('Daniel Osei', 'Student President', 'Computer Engineering', 'Focused on academic excellence, leadership programs, and stronger student voice.', 'DO'),
('Mila Chen', 'Student President', 'Computer Engineering', 'Building an inclusive community with transparent communication and support.', 'MC');

ALTER TABLE candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow read access to candidates"
ON candidates FOR SELECT
USING (true);

CREATE POLICY "Allow read access to votes"
ON votes FOR SELECT
USING (true);

CREATE POLICY "Allow insert votes"
ON votes FOR INSERT
WITH CHECK (true);
